<?php
/**
 * @file
 * Field schema, install and uninstall functions for the social_field module.
 */

/**
 * Implements hook_field_schema().
 */
function socialfield_field_schema($field) {
  return array(
    'columns' => array(
      'service' => array(
        'type' => 'varchar',
        'length' => 32,
      ),
      'url' => array(
        'type' => 'varchar',
        'length' => 255,
      ),
      'weight' => array(
        'type' => 'int',
        'size' => 'small',
      ),
    ),
  );
}

/**
 * Moves Socialfield settings from variable to config.
 */
function socialfield_update_1000() {
  $services = update_variable_get('socialfield_services', socialfield_default_services());
  $config = config('socialfield.settings');
  $config->set('services', $services);
  $config->save();

  update_variable_del('socialfield_services');
}

/**
 * Update socialfield settings.
 */
function socialfield_update_1001() {
  $config = config('socialfield.settings');
  $services = $config->get('services');
  if (empty($services) || !is_array($services)) {
    $services = array();
  }
  $default_services = socialfield_default_services();

  foreach ($services as $service_name => $service_info) {
    // Mark the service as enabled.
    $services[$service_name]['enabled'] = TRUE;
    // Add a service name key.
    $services[$service_name]['service_name'] = $service_name;
    // Change the 'name' key to 'label'.
    if (isset($services[$service_name]['name'])) {
      $services[$service_name]['label'] = $services[$service_name]['name'];
      unset($services[$service_name]['name']);
    }
    // Change the 'icon' key to 'icon_css'.
    if (isset($services[$service_name]['icon'])) {
      $services[$service_name]['icon_css'] = $services[$service_name]['icon'];
      unset($services[$service_name]['icon']);
    }
    // Add the icon API info.
    if (isset($default_services[$service_name])) {
      $services[$service_name]['iconapi'] = $default_services[$service_name]['iconapi'];
      $services[$service_name]['iconapi_fill'] = $default_services[$service_name]['iconapi_fill'];
      // Remove the default service if it had been overridden.
      unset($default_services[$service_name]);
    }
  }

  // Add the other default services as disabled.
  foreach ($default_services as $service_name => $service_info) {
    $services[$service_name] = $default_services[$service_name];
    $services[$service_name]['enabled'] = FALSE;
  }

  $config->set('services', $services);
  $config->save();
}

/**
 * Update socialfield settings.
 */
function socialfield_default_services() {
  $services = array(
    "facebook" => array(
      "label" => "Facebook",
      "service_name" => 'facebook',
      "icon_css" => "icon-facebook",
      "iconapi" => "facebook-logo",
      "iconapi_fill" => "facebook-logo-fill",
      "validation_pattern" => "*facebook.com/*",
      "enabled" => TRUE,
    ),
    "twitter" => array(
      "label" => "Twitter",
      "service_name" => 'twitter',
      "icon_css" => "icon-twitter",
      "iconapi" => "twitter-logo",
      "iconapi_fill" => "twitter-logo-fill",
      "validation_pattern" => "*twitter.com/*",
      "enabled" => TRUE,
    ),
    "x" => array(
      "label" => "X",
      "service_name" => 'x',
      "icon_css" => "icon-twitter",
      "iconapi" => "x-logo",
      "iconapi_fill" => "x-logo-fill",
      "validation_pattern" => "*x.com/*",
      "enabled" => TRUE,
    ),
    "instagram" => array(
      "label" => "Instagram",
      "service_name" => 'instagram',
      "icon_css" => "icon-instagram",
      "iconapi" => "instagram-logo",
      "iconapi_fill" => "instagram-logo-fill",
      "validation_pattern" => "*instagram.com/*",
      "enabled" => TRUE,
    ),
    "linkedin" => array(
      "label" => "LinkedIn",
      "service_name" => 'linkedin',
      "icon_css" => "icon-linkedin",
      "iconapi" => "linkedin-logo",
      "iconapi_fill" => "linkedin-logo-fill",
      "validation_pattern" => "*linkedin.com/*",
      "enabled" => TRUE,
    ),
    "youtube" => array(
      "label" => "YouTube",
      "service_name" => 'youtube',
      "icon_css" => "icon-youtube",
      "iconapi" => "youtube-logo",
      "iconapi_fill" => "youtube-logo-fill",
      "validation_pattern" => "*youtube.com/*",
      "enabled" => TRUE,
    ),
    "vimeo" => array(
      "label" => "Vimeo",
      "service_name" => 'vimeo',
      "icon_css" => "icon-vimeo",
      "iconapi" => "video",
      "iconapi_fill" => "video-fill",
      "validation_pattern" => "*vimeo.com/*",
      "enabled" => TRUE,
    ),
    "flickr" => array(
      "label" => "Flickr",
      "service_name" => 'flickr',
      "icon_css" => "icon-flickr",
      "iconapi" => "camera",
      "iconapi_fill" => "camera-fill",
      "validation_pattern" => "*flickr.com/*",
      "enabled" => TRUE,
    ),
    "pinterest" => array(
      "label" => "Pinterest",
      "service_name" => 'pinterest',
      "icon_css" => "icon-pinterest",
      "iconapi" => "pinterest-logo",
      "iconapi_fill" => "pinterest-logo-fill",
      "validation_pattern" => "*pinterest.com/*",
      "enabled" => TRUE,
    ),
    "github" => array(
      "label" => "GitHub",
      "service_name" => "github",
      "icon_css" => "icon-github",
      "iconapi" => "github-logo",
      "iconapi_fill" => "github-logo-fill",
      "validation_pattern" => "*github.com/*",
      "enabled" => TRUE,
    ),
  );
  return $services;
}
